## Use Github Actions to build sailfishos rpms
## Copy from https://github.com/CODeRUS/screencast
## Thanks CODeRUS

name: Build Tbclient

on:
  push:
    tags:
      - '*'
    branches:
      - master
env:
  RELEASE: 4.1.0.23

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir output

    - name: Build armv7hl
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /share/* . ;
            mb2 -t SailfishOS-$RELEASE-armv7hl qmake ;
            mb2 -t SailfishOS-$RELEASE-armv7hl build ;
            sudo cp -r RPMS/*.rpm /share/output"

    - name: Build i486
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /share/* . ;
            mb2 -t SailfishOS-$RELEASE-i486 qmake ;
            mb2 -t SailfishOS-$RELEASE-i486 build ;
            sudo cp -r RPMS/*.rpm /share/output"

    - name: Build aarch64
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk-aarch64:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /share/* . ;
            mb2 -t SailfishOS-$RELEASE-aarch64 qmake ;
            mb2 -t SailfishOS-$RELEASE-aarch64 build ;
            sudo cp -r RPMS/*.rpm /share/output"

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: harbour-tbclient-rpms.zip
        path: output
